In [31]:
import numpy as np
datas = []#2차원 리스트
f = open('Untitled.txt', 'r')
while True:
    s = f.readline() #s:'1,aaa,67,87,56\n'
    if s=='':
        break
    k = s.split('\n') #s:'1,aaa,67,87,56' : ''
    s = k[0]
    stu = s.split(',')  #stu: ['1', 'aaa', '67', '87', '56']
    for i in range(0, 2):
        stu.append(0)#stu: ['1', 'aaa', '67', '87', '56', 0 , 0]
    datas.append(stu)
    
f.close()

arr = np.array(datas) #datas리스트를 numpy 배열로 변환
names = arr[:, 0]  #모든 줄 0번컬럼(이름)만 추출하여 names에 저장
x = arr[:, 1:]  #모든 줄 1~끝컬럼(번호,국,영,수) 추출해서 x에 저장
score = x.astype(np.float32)  #점수 배열 요소 타입을 float으로 변경
'''
for i in score:        # 모든 줄의 총점 평균 계산. 
    k = i[1:4]           #k: [국,영,수]
    sum1 = k.sum()
    i[4]=sum1
    i[5]=sum1/3
'''    
score[:, 4]=score[:,1:4].sum(axis=1)
score[:, 5]=score[:, 4]/3

print('각 학생의 총점 평균')
for i in range(0, 5):
    print(names[i], end='\t')
    print(score[i])

#학생들의 국어총점, 영어총점, 수학총점
sums = score.sum(axis=0)
print('국어총점:', sums[1])
print('영어총점:', sums[2])
print('수학총점:', sums[3])
print('전체총점:', sums[4])
print('전체평균합:', sums[5])

#총점 정렬
#score[:, 4].sort(): 총점방만 정렬

#버블소트
for i in range(0, 4):
    for j in range(0, 4-i):
        if score[j][4]<score[j+1][4]:
            #score 배열 교체
            for k in range(0, len(score[j])):
                tmp = score[j][k]
                score[j][k]=score[j+1][k]
                score[j+1][k]=tmp
              
            #이름 바꿈
            tmp = names[j]
            names[j]=names[j+1]
            names[j+1]=tmp
            
for i in range(0, 5):
    print(names[i], end='\t')
    print(score[i])

각 학생의 총점 평균
aaa	[  1.  67.  87.  56. 210.  70.]
bbb	[  2.  65.  45.  34. 144.  48.]
ccc	[  3.        87.        65.        54.       206.        68.666664]
ddd	[  4.  98.  87.  76. 261.  87.]
eee	[  5.        54.        65.        87.       206.        68.666664]
국어총점: 371.0
영어총점: 349.0
수학총점: 307.0
전체총점: 1027.0
전체평균합: 342.3333
ddd	[  4.  98.  87.  76. 261.  87.]
aaa	[  1.  67.  87.  56. 210.  70.]
ccc	[  3.        87.        65.        54.       206.        68.666664]
eee	[  5.        54.        65.        87.       206.        68.666664]
bbb	[  2.  65.  45.  34. 144.  48.]


In [8]:
names

array(['aaa', 'bbb', 'ccc', 'ddd', 'eee'], dtype='<U11')

In [32]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [33]:
a>1

array([False, False,  True,  True,  True])

In [34]:
a<4

array([ True,  True,  True,  True, False])

In [36]:
a

array([0, 1, 2, 3, 4])

In [35]:
a<1

array([ True, False, False, False, False])

In [37]:
a>3

array([False, False, False, False,  True])

In [1]:
import pandas as pd
s1 = pd.Series(['aaa', 'bbb', 'ccc'])
s1

0    aaa
1    bbb
2    ccc
dtype: object

In [2]:
s1[0]

'aaa'

In [3]:
s1[1:3]

1    bbb
2    ccc
dtype: object

In [4]:
s2 = pd.Series({'kor':65, 'eng':78, 'math':89})
s2

kor     65
eng     78
math    89
dtype: int64

In [5]:
s2['kor']

65

In [6]:
s2['math']

89

In [15]:
idx = [] #사용할 인덱스 
vals = [] #시리즈로 생성할 값 

#학생들 이름 리스트
names = ['aaa', 'bbb', 'ccc', 'ddd', 'eee']

for i in range(0, 5):#인덱스와 성적 자동 생성
    s = 'student'+str(i+1)  #인덱스로 사용할 문자열 생성
    idx.append(s) #생성한 인덱스를 idx에 저장
    
    #한사람의 이름과 성적을 한 리스트에 담음
    val =[names[i], np.random.randint(0,100, (3))]
    vals.append(val)
    
stu = pd.Series(vals, index=idx)
stu

student1    [aaa, [34, 95, 18]]
student2    [bbb, [52, 85, 25]]
student3     [ccc, [13, 54, 8]]
student4      [ddd, [6, 0, 20]]
student5    [eee, [16, 38, 45]]
dtype: object

In [9]:
idx

['student1', 'student2', 'student3', 'student4', 'student5']

In [10]:
vals

[array([80,  8, 39]),
 array([ 0, 94, 55]),
 array([55, 67, 52]),
 array([30, 86, 37]),
 array([87, 59, 24])]

In [16]:
data=[[1,2,3],[4,5,6],[7,8,9]]
d1 = pd.DataFrame(data)
d1

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [17]:
index = ['stu1','stu2','stu3','stu4']
cols = ['name' ,'num', 'kor', 'eng', 'math']
vals = [['aaa', 1, 54,56,67],
        ['bbb', 2, 98,76,56],
        ['ccc', 3, 78,89,54], 
        ['ddd', 4, 96,35,86]]
d2 = pd.DataFrame(vals, index=index, columns=cols)
d2

name  num  kor  eng  math
stu1  aaa    1   54   56    67
stu2  bbb    2   98   76    56
stu3  ccc    3   78   89    54
stu4  ddd    4   96   35    86

In [18]:
d2.index

Index(['stu1', 'stu2', 'stu3', 'stu4'], dtype='object')

In [19]:
d2.columns

Index(['name', 'num', 'kor', 'eng', 'math'], dtype='object')

In [20]:
d2.values

array([['aaa', 1, 54, 56, 67],
       ['bbb', 2, 98, 76, 56],
       ['ccc', 3, 78, 89, 54],
       ['ddd', 4, 96, 35, 86]], dtype=object)

In [22]:
dic = {
    'name':['aaa','bbb','ccc','ddd'],
    'num':[1,2,3,4],
    'kor':[76,56,87,76],
    'eng':[89,56,45,78],
    'math':[98,56,43,23]
}
idx = np.arange(1, 5)
d3 = pd.DataFrame(dic, index=idx)
d3

name  num  kor  eng  math
1  aaa    1   76   89    98
2  bbb    2   56   56    56
3  ccc    3   87   45    43
4  ddd    4   76   78    23

In [26]:
data = pd.read_csv('c.csv', encoding='euc-kr')
data

발생년    사고건수  사망자수   중상자수    경상자수  부상신고자수
0  2015  232035  4621  92522  233646   24232
1  2016  220917  4292  82463  226283   22974
2  2017  216335  4185  78212  223200   21417
3  2018  217148  3781  74258  227511   21268
4  2019  229600  3349  72306  245524   23882

In [27]:
data.describe()

발생년           사고건수         사망자수          중상자수           경상자수  \
count     5.000000       5.000000     5.000000      5.000000       5.000000   
mean   2017.000000  223207.000000  4045.600000  79952.200000  231232.800000   
std       1.581139    7210.825161   491.552439   8034.621534    8845.056851   
min    2015.000000  216335.000000  3349.000000  72306.000000  223200.000000   
25%    2016.000000  217148.000000  3781.000000  74258.000000  226283.000000   
50%    2017.000000  220917.000000  4185.000000  78212.000000  227511.000000   
75%    2018.000000  229600.000000  4292.000000  82463.000000  233646.000000   
max    2019.000000  232035.000000  4621.000000  92522.000000  245524.000000   

             부상신고자수  
count      5.000000  
mean   22754.600000  
std     1369.400526  
min    21268.000000  
25%    21417.000000  
50%    22974.000000  
75%    23882.000000  
max    24232.000000

In [51]:
data = pd.read_csv('d.csv', encoding='euc-kr')
data

가해자연령층   월  사고건수  사망자수  중상자수  경상자수  부상신고자수
0   20세이하   1   423    10   134   371      88
1   20세이하   2   405     6   128   397      81
2   20세이하   3   569    13   197   535      97
3   20세이하   4   595    11   175   578     117
4   20세이하   5   714     9   210   661     142
..    ...  ..   ...   ...   ...   ...     ...
91     불명   8   318     0    44   234      91
92     불명   9   376     0    50   237     125
93     불명  10   391     0    65   277      90
94     불명  11   432     0    53   331      99
95     불명  12   382     0    54   271      99

[96 rows x 7 columns]

In [59]:
a = data[data.columns[1:]].loc[:11]
a

월  사고건수  사망자수  중상자수  경상자수  부상신고자수
0    1   423    10   134   371      88
1    2   405     6   128   397      81
2    3   569    13   197   535      97
3    4   595    11   175   578     117
4    5   714     9   210   661     142
5    6   722     5   208   661     148
6    7   706     6   229   647     157
7    8   649     3   197   614     131
8    9   634     6   196   580     111
9   10   675     9   197   647     145
10  11   645    11   203   611     136
11  12   494     6   153   502     104

In [60]:
val=a.values
title = data['가해자연령층'][0]
cols=[[title,title,title,title,title,title], data.columns[1:]]
x = pd.DataFrame(val, columns=cols)
x

20세이하                           
       월 사고건수 사망자수 중상자수 경상자수 부상신고자수
0      1  423   10  134  371     88
1      2  405    6  128  397     81
2      3  569   13  197  535     97
3      4  595   11  175  578    117
4      5  714    9  210  661    142
5      6  722    5  208  661    148
6      7  706    6  229  647    157
7      8  649    3  197  614    131
8      9  634    6  196  580    111
9     10  675    9  197  647    145
10    11  645   11  203  611    136
11    12  494    6  153  502    104